import Head from 'next/head'
import Image from 'next/image'
import RecentBin from '../components/RecentBin'

export default function Home() {
  return (
    <div className="bg-gray-900 overflow-x-auto h-screen">
      <Head>
        <title className="bg-green-300">Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300&display=swap" rel="stylesheet"/>
        <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'></link>
        
      </Head>
      <navbar className="flex items-center bg-gray-800 w-screen h-10 left-0 box-border p-6">
          <div className="flex">
            <h1 className="text-center text-white text-3xl font-normal" style={{fontFamily:"Josefin Sans', sans-serif"}}>Paste-Bin</h1>
            <button className="bg-green-500 text-white ml-10 font-normal rounded px-5 py-1 transition-all duration-300 create-but">
              Create Now
            </button>
          </div>
          <div className="flex right-0 absolute mr-5">
          <button className="bg-gray-700 ml-5 text-white rounded px-5 py-1.5">
              Login
            </button>
            <button className="bg-gray-700 ml-5 text-white rounded px-5 py-1.5">
              Join Us
            </button>

          </div>
      </navbar>

      <main className="flex justify-center mt-5">
        <div className="bg-gray-800 ml-10 rounded-xl pt-2 pl-2 pr-2 pb-1 overflow-y-none relative">
          <div className="flex flex-row justify-between">  
            <p className="text-white ml-0.5" style={{fontFamily:'Consolas'}}>New Paste</p>
            <button className="bg-green-500 rounded-xl p-0.5 px-4 absolute right-0 top-0"><i class='bx bx-plus text-white text-2xl' ></i></button>
          </div>
          <textarea className="bg-gray-900 rounded-xl focus:outline-none p-3 text-white scrollbar" rows="15" cols="75" style={{resize:'none'}}></textarea>
        </div>
        <div className="bg-gray-800 w-4/12 ml-10 rounded-xl p-2">
          <div className="">
            <p className="text-white" style={{fontFamily:'Consolas'}}>Recent Bins</p>
              <div className="flex flex-col overflow-y-auto p-0.5 rounded-xl h-96 scrollbar">
                <RecentBin recentBinProf="Denyow" binDesc="Abi python yazdim bi bak hele"></RecentBin>
                <RecentBin recentBinProf="Denyow" binDesc="Abi python yazdim bi bak hele"></RecentBin>
                <RecentBin recentBinProf="Denyow" binDesc="Abi python yazdim bi bak hele"></RecentBin>
                <RecentBin recentBinProf="Denyow" binDesc="Abi python yazdim bi bak hele"></RecentBin>
                <RecentBin recentBinProf="Denyow" binDesc="Abi python yazdim bi bak hele"></RecentBin>
                <RecentBin recentBinProf="Denyow" binDesc="Abi python yazdim bi bak hele"></RecentBin>
                <RecentBin recentBinProf="Denyow" binDesc="Abi python yazdim bi bak hele"></RecentBin>
                <RecentBin recentBinProf="Denyow" binDesc="Abi python yazdim bi bak hele"></RecentBin>
                <RecentBin recentBinProf="Denyow" binDesc="Abi python yazdim bi bak hele"></RecentBin>
                <RecentBin recentBinProf="Denyow" binDesc="Abi python yazdim bi bak hele"></RecentBin>
                <RecentBin recentBinProf="Denyow" binDesc="Abi python yazdim bi bak hele"></RecentBin>
                <RecentBin recentBinProf="Denyow" binDesc="Abi python yazdim bi bak hele"></RecentBin>
              </div>
          </div>
        </div>
      </main>
    </div>
  )
}
